name: Cypress Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'  # Runs every day at 8:00 AM UTC, adjust the time as needed

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Cypress Tests 
        uses: cypress-io/github-action@v6

      # Artifacts
      - uses: actions/upload-artifact@v4
        name: Upload screenshots in case of failure
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
